// <auto-generated />
using LabT2Dependency.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace LabT2Dependency.Migrations
{
    [DbContext(typeof(TravelContext))]
    partial class TravelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LabT2Dependency.Models.Costumer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Name");

                    b.Property<string>("Occupation");

                    b.Property<bool>("TravelsWithAnimal");

                    b.HasKey("Id");

                    b.ToTable("Costumers");
                });

            modelBuilder.Entity("LabT2Dependency.Models.Journey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AnimalsAllowed");

                    b.Property<int?>("CostumerId");

                    b.Property<double>("Distance");

                    b.Property<string>("EndPosition");

                    b.Property<string>("StartPosition");

                    b.HasKey("Id");

                    b.HasIndex("CostumerId");

                    b.ToTable("Journeys");
                });

            modelBuilder.Entity("LabT2Dependency.Models.Journey", b =>
                {
                    b.HasOne("LabT2Dependency.Models.Costumer")
                        .WithMany("Journeys")
                        .HasForeignKey("CostumerId");
                });
#pragma warning restore 612, 618
        }
    }
}
